/* This source code in this file is licensed to You by Castle Technology
 * Limited ("Castle") and its licensors on contractual terms and conditions
 * ("Licence") which entitle you freely to modify and/or to distribute this
 * source code subject to Your compliance with the terms of the Licence.
 * 
 * This source code has been made available to You without any warranties
 * whatsoever. Consequently, Your use, modification and distribution of this
 * source code is entirely at Your own risk and neither Castle, its licensors
 * nor any other person who has contributed to this source code shall be
 * liable to You for any loss or damage which You may suffer as a result of
 * Your use, modification or distribution of this source code.
 * 
 * Full details of Your rights and obligations are set out in the Licence.
 * You should have received a copy of the Licence with this source code file.
 * If You have not received a copy, the text of the Licence is available
 * online at www.castle-technology.co.uk/riscosbaselicence.htm
 */
/* Created by Hdr2H.  Do not edit.*/
#ifndef H_ALLWINNERH3_H
#define H_ALLWINNERH3_H

#pragma force_top_level
#pragma include_only_once

#define SRAM_A1                                  (0x0)
#define SRAM_A1_Size                             (0x10000)
#define SRAM_A2                                  (0x44000)
#define SRAM_A2_Size                             (0x8000)
#define SRAM_C                                   (0x10000)
#define SRAM_C_Size                              (0xb000)
#define IO_Base                                  (0x1000000)
#define IO_Size                                  (0xf03c00)
#define DE                                       (0x1000000)
#define DE_Size                                  (0x400000)
#define DeInt                                    (0x1400000)
#define DeInt_Size                               (0x20000)
#define SysCtrl                                  (0x1c00000)
#define SysCtrl_Size                             (0x1000)
#define DMA                                      (0x1c02000)
#define DMA_Size                                 (0x1000)
#define NFDC                                     (0x1c03000)
#define NFDC_Size                                (0x1000)
#define TS                                       (0x1c06000)
#define TS_Size                                  (0x1000)
#define Key_Mem                                  (0x1c0b000)
#define KeyMem_Size                              (0x1000)
#define LCD_0                                    (0x1c0c000)
#define LCD_0_Size                               (0x1000)
#define LCD_1                                    (0x1c0d000)
#define LCD_1_Size                               (0x1000)
#define VE                                       (0x1c0e000)
#define VE_Size                                  (0x1000)
#define SDMMC_0                                  (0x1c0f000)
#define SDMMC_0_Size                             (0x1000)
#define SDMMC_1                                  (0x1c10000)
#define SDMMC_1_Size                             (0x1000)
#define SDMMC_2                                  (0x1c11000)
#define SDMMC_2_Size                             (0x1000)
#define SID                                      (0x1c14000)
#define SID_Size                                 (0x400)
#define Crypto                                   (0x1c15000)
#define Crypto_Size                              (0x1000)
#define MSG_BOX                                  (0x1c17000)
#define MSG_BOX_Size                             (0x1000)
#define SPINLOCK                                 (0x1c18000)
#define SPINLOCK_Size                            (0x1000)
#define USB_OTG_Dev                              (0x1c19000)
#define USB_OTG_Dev_Size                         (0x1000)
#define USB_OTG_xHCI_0                           (0x1c1a000)
#define USB_OTG_xHCI_0_Size                      (0x1000)
#define USB_HCI1                                 (0x1c1b000)
#define USB_HCI1_Size                            (0x1000)
#define USB_HCI2                                 (0x1c1c000)
#define USB_HCI2_Size                            (0x1000)
#define USB_HCI3                                 (0x1c1d000)
#define USB_HCI3_Size                            (0x1000)
#define SMC                                      (0x1c1e000)
#define SMC_Size                                 (0x1000)
#define CCU                                      (0x1c20000)
#define CCU_Size                                 (0x400)
#define PIO                                      (0x1c20800)
#define PIO_Size                                 (0x400)
#define TIMER                                    (0x1c20c00)
#define TIMER_Size                               (0x400)
#define OWA                                      (0x1c21000)
#define OWA_Size                                 (0x400)
#define PWM                                      (0x1c21400)
#define PWM_Size                                 (0x400)
#define KEYADC                                   (0x1c21800)
#define KEYADC_Size                              (0x400)
#define I2SPCM_0                                 (0x1c22000)
#define I2SPCM_0_Size                            (0x400)
#define I2SPCM_1                                 (0x1c22400)
#define I2SPCM_1_Size                            (0x400)
#define I2SPCM_2                                 (0x1c22800)
#define I2SPCM_2_Size                            (0x400)
#define AC                                       (0x1c22c00)
#define AC_Size                                  (0x800)
#define SMTA                                     (0x1c23400)
#define SMTA_Size                                (0x400)
#define THS                                      (0x1c25000)
#define THS_Size                                 (0x400)
#define UART_Offset                              (0x400)
#define UART_Base                                (0x1c28000)
#define UART_0                                   (0x1c28000)
#define UART_0_Size                              (0x400)
#define UART_1                                   (0x1c28400)
#define UART_1_Size                              (0x400)
#define UART_2                                   (0x1c28800)
#define UART_2_Size                              (0x400)
#define UART_3                                   (0x1c28c00)
#define UART_3_Size                              (0x400)
#define UART_Size                                (0x1000)
#define TWI_0                                    (0x1c2ac00)
#define TWI_0_Size                               (0x400)
#define TWI_1                                    (0x1c2b000)
#define TWI_1_Size                               (0x400)
#define TWI_2                                    (0x1c2b400)
#define TWI_2_Size                               (0x400)
#define SCR                                      (0x1c2c400)
#define SCR_Size                                 (0x400)
#define EMAC                                     (0x1c30000)
#define EMAC_Size                                (0x10000)
#define GPU                                      (0x1c40000)
#define GPU_Size                                 (0x10000)
#define HSTMR                                    (0x1c60000)
#define HSTMR_Size                               (0x1000)
#define DRAMCOM                                  (0x1c62000)
#define DRAMCOM_Size                             (0x1000)
#define DRAMCTL0                                 (0x1c63000)
#define DRAMCTL0_Size                            (0x1000)
#define DRAMPHY0                                 (0x1c69000)
#define DRAMPHY0_Size                            (0x1000)
#define SPI0                                     (0x1c68000)
#define SPI0_Size                                (0x1000)
#define SPI1                                     (0x1c69000)
#define SPI1_Size                                (0x1000)
#define SCU                                      (0x1c80000)
#define SCU_BASE_ADDR                            (SCU)
#define GIC_DIST                                 (SCU + GIC_DIST_Offset)
#define GIC_DIST_Offset                          (0x1000)
#define GIC_CPUIF_Offset                         (0x2000)
#define GIC_CPUIF                                (SCU + GIC_CPUIF_Offset)
#define MPU_INTC                                 (MPU_SCU)
#define MPU_SCU                                  (SCU)
#define MPU_GIC_PI                               (GIC_CPUIF)
#define MPU_GIC_ID                               (GIC_DIST)
#define MPU_INTC_DIST                            (GIC_DIST - SCU)
#define MPU_INTC_CPU                             (GIC_CPUIF - SCU)
#define CSI                                      (0x1cb0000)
#define CSI_Size                                 (0x50000)
#define TVE                                      (0x1e00000)
#define TVE_Size                                 (0x10000)
#define HDMI                                     (0x1ee0000)
#define HDMI_Size                                (0x20000)
#define RTC                                      (0x1f00000)
#define RTC_Size                                 (0x400)
#define R_TIMER                                  (0x1f00800)
#define R_TIMER_Size                             (0x400)
#define R_INTC                                   (0x1f00c00)
#define R_INTC_Size                              (0x400)
#define R_WDOG                                   (0x1f01000)
#define R_WDOG_Size                              (0x400)
#define R_PRCM                                   (0x1f01400)
#define R_PRCM_Size                              (0x400)
#define R_TWD                                    (0x1f01800)
#define R_TWD_Size                               (0x400)
#define R_CPUCFG                                 (0x1f01c00)
#define R_CPUCFG_Size                            (0x400)
#define R_CIR_RX                                 (0x1f02000)
#define R_CIR_RX_Size                            (0x400)
#define R_TWI                                    (0x1f02400)
#define R_TWI_Size                               (0x400)
#define R_UART                                   (0x1f02800)
#define R_UART_Size                              (0x400)
#define R_PIO                                    (0x1f02c00)
#define R_PIO_Size                               (0x400)
#define R_PWM                                    (0x1f03800)
#define R_PWM_Size                               (0x400)
#define CS_Debug                                 (0x3f500000)
#define CS_Debug_Size                            (0x20000)
#define TSGEN_RO                                 (0x3f506000)
#define TSGEN_RO_Size                            (0x1000)
#define TSGEN_CTRL                               (0x3f507000)
#define TSGEN_CTRL_Size                          (0x1000)
#define SDRAM                                    (0x40000000)
#define SDRAM_Size                               (0x80000000)
#define N_BROM                                   (0xffff0000)
#define N_BROM_Size                              (0x8000)
#define S_BROM                                   (0xffff0000)
#define S_BROM_Size                              (0x10000)
#define STACK_BASE                               (0x40000000)
#define STACK_SIZE                               (0x1000)
#endif
