# Makefile for SyncLib

COMPONENT   = SyncLib
HDRS        = atomic barrier cpuevent      mutex spin spinrw synclib
OBJS        = atomic barrier cpuevent init mutex spin spinrw

include CLibrary

# Dynamic dependencies:
